name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Build and Test
        run: |
          sbt compile
          sbt test
          sbt assembly

      - name: Build Docker image
        run: docker build -t todo-api:latest .

      - name: Push Docker image (optional)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag todo-api:latest laithanhtung/todo-api:latest
          docker push laithanhtung/todo-api:latest